import { useEffect, useState } from "react";
import { db } from "../firebase";
import { doc, onSnapshot } from "firebase/firestore";

/**
 * SENTINEL Phase 3 — Production AI SitRep Panel
 * Listen to /sessions/current for the Gemini-generated Situation Report.
 * This report is generated by the Cloud Function (backend/cloud-functions/gemini-trigger).
 */
export default function SitRepPanel() {
  const [sitrep, setSitrep] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    // Listen to the session document written by the Gemini Cloud Function
    const unsub = onSnapshot(doc(db, "sessions", "current"), (snap) => {
      setLoading(false);
      if (snap.exists()) {
        const data = snap.data();
        if (data.sitrep_error) {
          setError(data.sitrep_error);
          setSitrep(null);
        } else if (data.current_sitrep) {
          setSitrep(data.current_sitrep);
          setError(null);
        }
      } else {
        setSitrep(null);
        setError("Session data not found.");
      }
    }, (err) => {
      console.error("Firestore SitRep error:", err);
      setError("Failed to sync with SENTINEL AI.");
      setLoading(false);
    });

    return () => unsub();
  }, []);

  if (loading) return (
    <div style={{ padding: "1.5rem", textAlign: "center", color: "var(--accent-color, #6366f1)" }}>
      <div className="pulse" style={{ fontWeight: 800 }}>🤖 Syncing with Root AI Agent...</div>
    </div>
  );

  if (error) return (
    <div style={{ padding: "1.2rem", color: "#ef4444", border: "1px solid #ef444433", borderRadius: "10px", background: "rgba(239, 68, 68, 0.05)" }}>
      <strong>⚠️ AI Sync Error:</strong> {error}
    </div>
  );

  if (!sitrep) return (
    <div style={{ padding: "1.2rem", opacity: 0.5, textAlign: "center", border: "1px dashed rgba(255,255,255,0.1)", borderRadius: "10px" }}>
      System Nominal. All hospital zones monitored. Awaiting first incident analysis.
    </div>
  );

  const color = sitrep.severity === "P0" ? "var(--accent)" : "var(--neon-orange)";

  const handleSpeak = () => {
    const text = `Severity ${sitrep.severity}. ${sitrep.threat_summary}. Recommended actions: ${sitrep.recommended_actions?.join(", ")}`;
    const utterance = new SpeechSynthesisUtterance(text);
    window.speechSynthesis.speak(utterance);
  };

  return (
    <div className="animate-in" style={{ 
      fontFamily: "JetBrains Mono",
      color: "var(--text-main)",
      fontSize: "0.7rem"
    }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1.25rem", borderBottom: `1px solid ${color}33`, paddingBottom: "0.5rem" }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <div style={{ width: '6px', height: '6px', background: color, boxShadow: `0 0 8px ${color}` }} />
          <span style={{ fontWeight: 700, color }}>LVL::{sitrep.severity}</span>
        </div>
        <button
          onClick={handleSpeak}
          className="btn"
          style={{ padding: "2px 8px", fontSize: "0.5rem", height: 'auto' }}
        >VOICE_LINK</button>
      </div>

      <div style={{ marginBottom: "1.5rem", opacity: 0.9, lineHeight: 1.5, letterSpacing: '0.05em' }}>
        {sitrep.threat_summary?.toUpperCase()}
      </div>

      <div style={{ display: "flex", flexDirection: 'column', gap: "8px", marginBottom: "1.5rem" }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid var(--border-dim)', paddingBottom: '4px' }}>
          <span style={{ color: 'var(--text-muted)' }}>SECTORS_SAFE:</span>
          <span style={{ color: "var(--neon-green)" }}>{sitrep.safe_exits?.join(" | ") || "SEARCHING"}</span>
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid var(--border-dim)', paddingBottom: '4px' }}>
          <span style={{ color: 'var(--text-muted)' }}>SECTORS_BLOCKED:</span>
          <span style={{ color: "var(--accent)" }}>{sitrep.blocked_exits?.join(" | ") || "NONE"}</span>
        </div>
      </div>

      {sitrep.recommended_actions?.length > 0 && (
        <div>
          <div style={{ color: "var(--primary)", fontWeight: 700, marginBottom: "8px", fontSize: '0.6rem' }}>// RECOMMENDED_PROCEDURES</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
            {sitrep.recommended_actions.map((action, i) => (
              <div key={i} style={{ display: 'flex', gap: '8px', opacity: 0.7 }}>
                <span>0{i+1}_</span>
                <span>{action.toUpperCase()}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
